name: HerdingCats Unit Tests

on:
  push:
    branches:
      - main
    paths:
      - "HerdingCats/**"
      - "tests/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest requests loguru pandas polars duckdb==1.0.0 boto3

      - name: Create pytest.ini
        run: |
          echo "[pytest]" > pytest.ini
          echo "pythonpath = HerdingCats/" >> pytest.ini

      - name: Run tests
        run: pytest tests/
