name: Herding Cats Unit Tests
on:
  push:
    branches:
      - main
    paths:
      - "src/**"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install pytest
        run: pip install pytest requests loguru
      - name: Run tests
        run: pytest tests/
