name: HerdingCats Linting

on:
  push:
    branches:
      - main
    paths:
      - "**/*.py"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Create Ruff config
        run: |
          echo "[tool.ruff]" > pyproject.toml
          echo "ignore = [\"F841\"]" >> pyproject.toml

      - name: Run Ruff linting
        run: ruff check .

      - name: Run Ruff formatting
        run: ruff format .
